// frontend/src/pages/Workspace/components/WorkspaceHeader.tsx
import { Link } from "react-router";
import { useTranslation } from "react-i18next";
import { FaArrowLeft, FaPlus } from "react-icons/fa";
import { IoMdSettings } from "react-icons/io";

import type { Workspace } from "@/types/Workspace";
import { Button } from "@/components/ui/button";

interface WorkspaceHeaderProps {
  workspace: Workspace;
}

const WorkspaceHeader = ({ workspace }: WorkspaceHeaderProps) => {
  const { t } = useTranslation("workspace");

  return (
    <header className="grid grid-rows-2 gap-2">
      <div className="flex justify-between">
        <div className="flex items-center gap-2">
          <Button>
            <Link
              to={"/workspace"}
              className="flex items-center gap-2 transition-transform"
            >
              <FaArrowLeft />
              <p>{t("back")}</p>
            </Link>
          </Button>
          # {workspace.name}
        </div>
        <div className="flex gap-2">
          <Button>
            <FaPlus />
            {t("addMemberButton")}
          </Button>
          <Button>
            <IoMdSettings />
            {t("settingsButton")}
          </Button>
        </div>
      </div>
      <div className="bg-blue-500"></div>
    </header>
  );
};

export default WorkspaceHeader;

// frontend/src/components/workspace/WorkspaceHeader.vue
<script setup lang="ts">
import type { Workspace } from '../../types/workspace';

defineProps<
  {
    workspace: Workspace
  }
>()
</script>

<template>
    <header
        class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 p-4 bg-base-100 shadow-md rounded-2xl"
    >

        <!-- Top side of header -->
        <div>
            <!-- Top left side -->
            <div class="flex gap-2 items-center">
                <RouterLink to="/">
                    <button class="btn btn-primary">Back</button>
                </RouterLink>
                <h3>{{workspace.name}}</h3>
            </div
            <!-- Top right side -->
            <div>

            </div>
        </div>

        <!--Bottom side of header  -->
        <div>

        </div>
    </header>
</template>
